services:
  pgdatabase:
    image: postgres:13
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=/run/secrets/postgres_pw
      - POSTGRES_DB=ny_taxi
    volumes:
      - "./ny_taxi_postgres_data:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"
    secrets:
      - postgres_pw
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=/run/secrets/pgadmin_pw
    ports:
      - "8080:80"
    secrets:
      - pgadmin_pw
secrets:
  postgres_pw:
    file: ./postgres_pw.txt
  pgadmin_pw:
    file: ./pgadmin_pw.txt